name:  Build, Release & Publish JAR

on:
  push:
    branches:
      - gitActions

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Determine Module
        run: |
          echo "Parsing commit message..."
          C_MESSAGE="${{ github.event.head_commit.message }}"
          MODULE=$(echo "$C_MESSAGE" | grep -oP '^\((\w+)\)' | tr -d '()')
          
          if [ -z "$M" ]; then
            echo "no module found, stopping"
            exit 1
          else
            echo "module found: $MODULE"
          fi