name:  Build, Release & Publish JAR

on:
  push:
    branches:
      - gitActions2

jobs:
  build-and-publish:
    if: contains(github.event.head_commit.message, 'version(')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: []

    steps:
      - name: Determine Module
        id: determine-module
        run: |
          echo "Parsing commit message..."
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MESSAGE" =~ version\(([a-zA-Z0-9_-]+)\):\ ([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            MODULE="${BASH_REMATCH[1]}"
            VERSION="${BASH_REMATCH[2]}"
            echo "Module to build: $MODULE"
            echo "Version: $VERSION"
            echo "::set-output name=module::$MODULE"
            echo "::set-output name=version::$VERSION"
          else
            echo "Commit message does not match the expected pattern."
            exit 1
          fi

      - name: Add module to matrix
        id: add-module
        if: ${{ steps.determine-module.outputs.module == matrix.module }}
        run: |
          echo "::set-output name=matrix::{\"module\":\"${{ steps.determine-module.outputs.module }}\"}"
          echo "module=${{ steps.determine-module.outputs.module }}" >> $GITHUB_ENV
          echo "version=${{ steps.determine-module.outputs.version }}" >> $GITHUB_ENV

      - name: Checkout code
        id: checkout
        if: ${{ steps.determine-module.outputs.module == matrix.module }}
        uses: actions/checkout@v3

      - name: Set up JDK 11
        id: setup-java
        if: ${{ steps.determine-module.outputs.module == matrix.module }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission for gradlew
        id: grant-permission
        if: ${{ steps.determine-module.outputs.module == matrix.module }}
        run: chmod +x ./gradlew

      - name: Build JAR
        id: build
        if: ${{ steps.determine-module.outputs.module == matrix.module }}
        run: |
          ./gradlew :${{ steps.determine-module.outputs.module }}:clean :${{ steps.determine-module.outputs.module }}:build

      - name: Delete Existing Release
        id: delete-release
        if: ${{ steps.determine-module.outputs.module == matrix.module }}
        run: |
          echo "Deleting existing release..."
          release_id=$(gh release list | grep ${{ steps.determine-module.outputs.version }} | awk '{print $1}')
          if [ -n "$release_id" ]; then
            gh release delete $release_id -y
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Existing Tag
        id: delete-tag
        if: ${{ steps.determine-module.outputs.module == matrix.module }}
        run: |
          echo "Deleting existing tag..."
          git tag -d ${{ steps.determine-module.outputs.version }} || true
          git push --delete origin ${{ steps.determine-module.outputs.version }} || true

      - name: Release JAR
        uses: actions/create-release@v1
        with:
          tag_name: ${{ matrix.version }}
          release_name: ${{ matrix.module }}-${{ matrix.version }}
          body: "Release of ${{ matrix.module }} version ${{ matrix.version }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create.outputs.upload_url }}
          asset_path: ${{ matrix.module }}/build/libs/*.jar
          asset_name: ${{ matrix.module }}-${{ matrix.version }}.jar
          asset_content_type: application/java-archive